image: node:15.12-alpine3.13
stages:
  - deploy
pages:
  stage: deploy
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

