services:
  cbam:
    build: .
    image: harbor.aipim.synology.me/lca/cbam-mini-demo@sha256:d397189025d8643286597ee50e6b7466721fa270cb7d85acd8fb2ff5c5a40bb7
    restart: 'always'
    ports:
      - 13731:80
  watchtower:
    image: containrrr/watchtower
    restart: 'always'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 5