version: '3'
services:
  cbam:
    build: .
    image: harbor.aipim.synology.me/lca/cbam-mini-demo:latest
    restart: 'always'
    ports:
      - 13731:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
