version: '3'
services:
  cbam:
    build: .
    image: harbor.aipim.synology.me/lca/cbam-mini-demo:85f217ce
    restart: 'always'
    ports:
      - 13731:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: containrrr/watchtower
    restart: 'always'
    environment:
      - WATCHTOWER_LABEL_ENABLE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
