FROM node:21.5-alpine3.19 AS builder

WORKDIR /app

RUN corepack enable

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install @redocly/cli

COPY ./spec.yaml ./spec.yaml

RUN pnpm build:api-doc

FROM nginx:1.25.3-alpine-slim AS runner

WORKDIR /app

COPY --from=builder /app/redoc-static.html /usr/share/nginx/html/index.html
