openapi: 3.0.0
info:
  title: CBAM demo API
  version: 0.1.0
  description: aa
paths:
  /:
    get:
      operationId: fetch
      summary: Fetch CBAM data
      responses:
        200:
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CBAM'
components:
  schemas:
    CBAM:
      type: object
      required:
        - reporting-period
        - installation
        - verifier
        - agcs
        - processes
      properties:
        reporting-period:
          type: object
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
        installation:
          type: object
          properties:
            name:
              type: string
            name-en:
              type: string
            street:
              type: string
            economic-activity:
              type: string
            postcode:
              type: integer
            po-box:
              type: string
            city:
              type: string
            country:
              type: string
            unlocode:
              type: string
            coordinates:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
            representative:
              type: string
            email:
              type: string
              format: email
            telephone:
              type: string
          required:
            - name-en
            - country
            - unlocode
        verifier:
          type: object
          properties:
            company-name:
              type: string
            street:
              type: string
            city:
              type: string
            postcode:
              type: string
            country:
              type: string
            name:
              type: string
            email:
              type: string
              format: email
            telephone:
              type: string
            fax:
              type: string
            accreditation-state:
              type: string
            national-accreditation-body:
              type: string
            registration-number:
              type: string
        agcs:
          type: array
          items:
            type: object
            properties:
              agc:
                $ref: '#/components/schemas/AGC'
              routes:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
        processes:
          type: array
          items:
            $ref: '#/components/schemas/Process'
    AGC:
      type: string
      enum:
        - Cement
        - Cement clinker
        - Calcined clays
        - Aluminous cement
        - Iron or steel products
        - Crude steel
        - Direct reduced iron
        - Pig iron
        - Alloys
        - Sintered Ore
        - Hydrogen
        - Ammonia
        - Nitric acid
        - Urea
        - Mixed fertilizers
        - Aluminium products
        - Unwrought aluminium
        - Electricity
    Route:
      type: string
      enum:
        - Basic oxygen steelmaking
    Process:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        agc:
          $ref: '#/components/schemas/AGC'
        included-goods:
          type: array
          items:
            $ref: '#/components/schemas/AGC'