openapi: 3.0.0
info:
  title: CBAM demo API
  version: 0.1.0
  description: aa
paths:
  /:
    get:
      operationId: fetch
      summary: Fetch CBAM data
      responses:
        200:
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
