openapi: 3.0.0
info:
  title: CBAM demo API
  version: 0.1.0
  description: aa
paths:
  /:
    get:
      operationId: fetch
      summary: Fetch CBAM data
      responses:
        200:
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CBAM'
components:
  schemas:
    CBAM:
      type: object
      properties:
        reporting-period:
          type: object
          description: CBAM 보고 기간
          properties:
            start:
              type: string
              format: date
              description: CBAM 보고 기간의 시작일
            end:
              type: string
              format: date
              description: CBAM 보고 기간의 종료일
        installation:
          type: object
          description: 설비 기본 정보
          properties:
            name:
              type: string
            name-en:
              type: string
            street:
              type: string
            economic-activity:
              type: string
            postcode:
              type: integer
            po-box:
              type: string
            city:
              type: string
            country:
              type: string
            unlocode:
              type: string
            coordinates:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
            representative:
              type: string
            email:
              type: string
              format: email
            telephone:
              type: string
          required:
            - name-en
            - country
            - unlocode
        verifier:
          type: object
          properties:
            company-name:
              type: string
            street:
              type: string
            city:
              type: string
            postcode:
              type: string
            country:
              type: string
            name:
              type: string
            email:
              type: string
              format: email
            telephone:
              type: string
            fax:
              type: string
            accreditation-state:
              type: string
            national-accreditation-body:
              type: string
            registration-number:
              type: string
        agcs:
          type: array
          description: 관련된 AGC 종류
          items:
            type: object
            properties:
              agc:
                $ref: '#/components/schemas/AGC'
              routes:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
        processes:
          type: array
          description: 제조 공정 목록
          items:
            $ref: '#/components/schemas/Process'
        precursors:
          type: array
          description: 구입한 프리커서 목록
          items:
            $ref: '#/components/schemas/Precursor'
        source-streams:
          type: array
          description: 소스 스트림 목록
          items:
            type: object
            properties:
              method:
                type: string
                description: 배출량 측정 방식
                enum:
                  - Combustion
                  - Process emissions
                  - Mass Balance
              name:
                type: string
                description: 본 스트림의 명칭
              ad:
                type: number
                description: 소비량 (Activity data)
              ad-unit:
                type: string
                description: 소비량 단위
                enum:
                  - t
                  - 1000Nm3
              ncv:
                type: number
                description: Net calorific value
        ghg-balance:
          type: object
          properties:
            co2:
              type: number
            biomass:
              type: number
            n2o:
              type: number
            pfc:
              type: number
            direct:
              type: number
            indirect:
              type: number
      required:
        - reporting-period
        - installation
        - verifier
        - agcs
        - processes
        - precursors
    AGC:
      type: string
      description: 집약 상품 카테고리
      enum:
        - Cement
        - Cement clinker
        - Calcined clays
        - Aluminous cement
        - Iron or steel products
        - Crude steel
        - Direct reduced iron
        - Pig iron
        - Alloys
        - Sintered Ore
        - Hydrogen
        - Ammonia
        - Nitric acid
        - Urea
        - Mixed fertilizers
        - Aluminium products
        - Unwrought aluminium
        - Electricity
    Route:
      type: string
      description: 생산 경로
      enum:
        - Basic oxygen steelmaking
    Process:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 식별자
        name:
          type: string
          description: 제조 공정 명칭
        agc:
          $ref: '#/components/schemas/AGC'
        included-goods:
          type: array
          items:
            $ref: '#/components/schemas/AGC'
        production-level:
          type: object
          description: 각 제조 경로별로 생산된 양
          additionalProperties:
            type: number
            description: 각 경로별로 생산된 양. 톤 단위.
        consumed:
          type: object
          description: 각 제조 공정에서 소비된 양
          additionalProperties:
            type: number
            description: 옆 공정에서 소비된 양. 톤 단위.
        attr:
          type: object
          description: 귀속배출량 계산
          properties:
            direm:
              type: number
              description: 직접배출량
            heat:
              type: object
              description: 측정가능한 열
              properties:
                imported:
                  type: object
                  description: 수입된 열
                  properties:
                    amount:
                      type: number
                      description: 수입된 양
                    ef:
                      type: number
                      description: 배출계수
                  required:
                    - amount
                    - ef
                exported:
                  type: object
                  description: 추출된 열
                  properties:
                    amount:
                      type: number
                      description: 수출된 양
                    ef:
                      type: number
                      description: 배출계수
                  required:
                    - amount
                    - ef
              required:
                - imported
                - exported
            wg:
              type: object
              description: 폐가스
              properties:
                imported:
                  type: object
                  description: 수입된 폐가스
                  properties:
                    amount:
                      type: number
                      description: 수입된 양
                    ef:
                      type: number
                      description: 배출계수
                  required:
                    - amount
                exported:
                  type: object
                  description: 수출된 폐가스
                  properties:
                    amount:
                      type: number
                      description: 수출된 양
                    ef:
                      type: number
                      description: 배출계수
                  required:
                    - amount
              required:
                - imported
                - exported
            electricity:
              type: object
              description: 전력
              properties:
                imported:
                  type: object
                  description: 수입된 전력
                  properties:
                    amount:
                      type: number
                      description: 수입된 양 (MWh)
                    ef:
                      type: number
                      description: 배출계수
                    source:
                      type: string
                      description: 배출계수 출처
                  required:
                    - amount
                    - ef
                    - source
                exported:
                  type: object
                  description: 수출된 전력 (간접배출량)
                  properties:
                    amount:
                      type: number
                      description: 수출된 양 (MWh)
                    ef:
                      type: number
                      description: 배출계수
                  required:
                    - amount
                    - ef
              required:
                - imported
                - exported
          required:
            - direm
            - electricity
    Precursor:
      type: object
      description: 프리커서
      properties:
        id:
          type: string
          format: uuid
          description: 식별자
        name:
          type: string
          description: 프리커서 명칭
        country:
          $ref: '#/components/schemas/CountryCode'
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
    CountryCode:
      type: string
      description: 국가 코드
      enum:
        - AD
        - AE
        - AF
        - AG
        - AI
        - AL
        - AM
        - AN
        - AO
        - AQ
        - AR
        - AS
        - AT
        - AU
        - AW
        - AX
        - AZ
        - BA
        - BB
        - BD
        - BE
        - BF
        - BG
        - BH
        - BI
        - BJ
        - BL
        - BM
        - BN
        - BO
        - BQ
        - BR
        - BS
        - BT
        - BV
        - BW
        - BY
        - BZ
        - CA
        - CC
        - CD
        - CF
        - CG
        - CH
        - CI
        - CK
        - CL
        - CM
        - CN
        - CO
        - CR
        - CU
        - CV
        - CW
        - CX
        - CY
        - CZ
        - DE
        - DJ
        - DK
        - DM
        - DO
        - DZ
        - EC
        - EE
        - EG
        - EH
        - ER
        - ES
        - ET
        - EU
        - FI
        - FJ
        - FK
        - FM
        - FO
        - FR
        - GA
        - GB
        - GD
        - GE
        - GF
        - GG
        - GH
        - GI
        - GL
        - GM
        - GN
        - GP
        - GQ
        - GR
        - GS
        - GT
        - GU
        - GW
        - GY
        - HK
        - HM
        - HN
        - HR
        - HT
        - HU
        - ID
        - IE
        - IL
        - IM
        - IN
        - IO
        - IQ
        - IR
        - IS
        - IT
        - JE
        - JM
        - JO
        - JP
        - KE
        - KG
        - KH
        - KI
        - KM
        - KN
        - KP
        - KR
        - KW
        - KY
        - KZ
        - LA
        - LB
        - LC
        - LI
        - LK
        - LR
        - LS
        - LT
        - LU
        - LV
        - LY
        - MA
        - MC
        - MD
        - ME
        - MF
        - MG
        - MH
        - MK
        - ML
        - MM
        - MN
        - MO
        - MP
        - MQ
        - MR
        - MS
        - MT
        - MU
        - MV
        - MW
        - MX
        - MY
        - MZ
        - NA
        - NC
        - NE
        - NF
        - NG
        - NI
        - NL
        - 'NO'
        - NP
        - NR
        - NU
        - NZ
        - OM
        - PA
        - PE
        - PF
        - PG
        - PH
        - PK
        - PL
        - PM
        - PN
        - PR
        - PS
        - PT
        - PW
        - PY
        - QA
        - QP
        - RE
        - RO
        - RS
        - RU
        - RW
        - SA
        - SB
        - SC
        - SD
        - SE
        - SG
        - SH
        - SI
        - SJ
        - SK
        - SL
        - SM
        - SN
        - SO
        - SR
        - SS
        - ST
        - SV
        - SX
        - SY
        - SZ
        - TC
        - TD
        - TF
        - TG
        - TH
        - TJ
        - TK
        - TL
        - TM
        - TN
        - TO
        - TP
        - TR
        - TT
        - TV
        - TW
        - TZ
        - UA
        - UG
        - UM
        - US
        - UY
        - UZ
        - VA
        - VC
        - VE
        - VG
        - VI
        - VN
        - VU
        - WF
        - WS
        - XA
        - XC
        - XI
        - XK
        - XL
        - XM
        - XO
        - XP
        - XR
        - XS
        - XZ
        - YE
        - YT
        - YU
        - ZA
        - ZM
        - ZR
        - ZW